### ISSUE TITLE
刚刚学mongodb，还有spring security 不知道怎么登陆。。

### ISSUE THREAD

**Issue by xieguanliang** [dotdoppler/Blog#2]
咋么才能登陆。
先谢谢了

**Comment by dotdoppler** [comment]
具体问题是怎样的呢？是无法访问登陆页面还是登陆不进去？

**Comment by dotdoppler** [comment]
你要先往Mongo里面插入一条User的文档

**Comment by xieguanliang** [comment]
对啊，插入了，用户名和密码都对，对的时候控制台没有输出，但是界面却没有跳转，而是清空了用户名密码。还有一个就是运行test那个mongodb，要求输入用户名和密码才能进去主页。

**Comment by dotdoppler** [comment]
插入的密码是加密后的吗？

**Comment by xieguanliang** [comment]
嗯

**Comment by xieguanliang** [comment]
我是往mongpdb 插入{ "_id" : ObjectId("5809a6d68f19e705362f8fae"), "createdAt" : "2016-01-01", "updatedAt" : "2016-10-01", "username" : "test", "email" : "12283519@qq.com", "password" : "$2a$10$LOqePml/koRGsk2YAIOFI.1YNKZg7EsQ5BAIuYP1nWOyYRl21dlne", "role" : "ADMIN" }
就是这样子，没有加密啊，直接这样子，框架还没有看懂。

**Comment by dotdoppler** [comment]
你加我qq 1003047085
